### ISSUE TITLE
【 BUG 】 Module causes 3-day waste clearing and dismissal!

### ISSUE THREAD

**Issue by lenmon666** [WarperSan/ShipInventory#1]
When I used this mod to play with three friends, we put in all the waste from the past three days! When we returned to the company building to use the terminal for viewing, it showed as empty, resulting in us not even achieving the target value of 130 before being fired!
I hope the author can investigate the cause of this issue and fix it! thank you!
At the same time, we hope that the author can add the repaired content of each version update when thunderstore updates the mod, so that we can check if the problems we encountered have been fixed!

**Comment by Doodlebug12** [comment]
Just experienced the same thing, we put in $1500 worth of items and ended up with an empty inventory while at the company.

**Comment by WarperSan** [comment]
I invite you to check the newest version of the [mod](https://thunderstore.io/c/lethal-company/p/WarperSan/ShipInventory). The "random inventory clear" was (afaik) fixed
