### ISSUE TITLE
[BUG] Incompat with cursedScraps

### ISSUE THREAD

**Issue by EarthApocalypto** [WarperSan/ShipInventory#11]
**Describe the bug**
If you pull out items with cursedScraps enabled, it will add curses to previously uncursed items. This bloats the item value/causes some desync as not all the curses are currently enabled by default.

**To Reproduce**
Pull out items with this mod enabled.

**Mods used**
https://thunderstore.io/c/lethal-company/p/Lega/CursedScraps/

**Comment by WarperSan** [comment]
Could not reproduce it. The items seem to stay uncursed. (v2.1.1)
