### ISSUE TITLE
[SUGGESTION] Make the player return to the scrap menu

### ISSUE THREAD

**Issue by WarperSan** [WarperSan/ShipInventory#13]
**Is your feature request related to a problem? Please describe.**
After confirming a scrap for retrieval, the terminal should return to the scrap menu instead of terminal root. It would make bulk item removal easier, instead of retrieving everything and putting the extra back in.

**Comment by minimusubi** [comment]
For a better user experience, alternatively, don't send the user back to the menu, and instead

1. Leave the user in the menu they selected (single item/type)
2. Keep the user on the same numbered page (unless the page doesn't exist anymore)
3. Don't reset the selection on the page (after choosing an item/type, don't move the selection to the top)
