### ISSUE TITLE
[BUG] Desync between host and clients

### ISSUE THREAD

**Issue by KleskReaver** [WarperSan/ShipInventory#14]
**Describe the bug**
Had an issue where the host was seeing the correct amount of scrap items and worth in the chute on the terminal screen but when clients looked at the terminal they saw a lower amount of both

**To Reproduce**
Not sure how to reproduce, perhaps clients joining an existing save, may have been after we left to re-host the game so we could get another player into the game

**Expected behavior (Optional)**
All players seeing the correct amount of scrap items and their worth, I assume this is just down to a lack of networking feature?

**Comment by minimusubi** [comment]
This happened to me as well- some clients saw the ship inventory was reduced or empty, when in fact it was not. In my case however, for what it's worth, we had 135 mods, so there may have been mod compatibility issues.

**Comment by WarperSan** [comment]
Same reasoning as [this one ](https://github.com/WarperSan/ShipInventory/issues/6#issuecomment-2359808940) (I assume).

If this is a different problem, simply let me know and I will reopen this issue.

**Comment by minimusubi** [comment]
In my case, I did not have GeneralImprovements installed.

This is the list of mods that were used:
<details><summary>Mod list</summary>
<p>

<pre>BepInEx-BepInExPack-5.4.2100
BMX-LobbyCompatibility-1.2.0
AinaVT-LethalConfig-1.4.2
flerouwu-LC_FastStartup-1.1.2
notnotnotswipez-MoreCompany-1.10.1
mattymatty-LobbyControl-2.4.4
Rune580-LethalCompany_InputUtils-0.7.7
quackandcheese-ToggleMute-1.3.1
taffyko-NameplateTweaks-1.0.7
mattymatty-AsyncLoggers-2.1.2
DiFFoZ-BepInEx_Faster_Load_AssetBundles_Patcher-0.6.4
DiFFoZ-HarmonyXTranspilerFix-1.1.0
DiFFoZ-LethalPerformance-0.4.0
fumiko-CullFactory-1.3.15
AdiBTW-Loadstone-0.1.14
ButteryStancakes-KickWithoutBan-1.0.0
Pooble-LCBetterSaves-1.7.3
Zehs-LCBetterSavesFix-1.0.0
mattymatty-Matty_Fixes_Experimental-1.1.24
Dev1A3-LethalFixes-1.2.2
ButteryStancakes-ButteryFixes-1.10.2
ButteryStancakes-EnemySoundFixes-1.5.9
ButteryStancakes-MeleeFixes-1.3.1
Zaggy1024-PathfindingLagFix-1.4.0
Hardy-LCMaxSoundsFix-1.2.0
Evaisa-HookGenPatcher-0.0.5
SylviBlossom-SmartItemSaving-1.2.4
FutureSavior-Boombox_Sync_Fix-1.1.3
itsmeowdev-DoorFix-1.0.0
AudioKnight-StarlancerAIFix-3.8.2
tinyhoot-ShipLoot-1.1.0
FlipMods-LetMeLookDown-1.0.2
taffyko-NiceChat-1.2.6
Renegades-FlashlightToggle-1.5.0
Renegades-WalkieUse-1.5.0
DarthLilo-WhoVoted-1.0.2
Dev1A3-BetterVehicleControls-1.1.3
akechii-DiscountAlert-2.3.0
NutNutty-SellTracker-1.2.1
phatisfat-ItemSlotNumKeys-1.0.0
FlipMods-ReservedItemSlotCore-2.0.37
FlipMods-ReservedFlashlightSlot-2.0.8
Evaisa-LethalLib-0.16.1
Entity378-SellBodiesFixed-1.10.1
TwinDimensionalProductions-CoilHeadStare-1.0.9
loaforc-loaforcsSoundAPI-1.1.7
LethalResonance-LETHALRESONANCE-4.7.1
egeadam-MoreScreams-1.0.3
ASmolBoy-Intro_Company_Speech_Extended_Remix-1.0.1
Verity-TooManySuits-1.1.2
x753-More_Suits-1.4.3
actibytes-SkellyGlowSuits-1.0.6
FlipMods-TooManyEmotes-2.2.7
taffyko-BetterSprayPaint-2.0.9
Piggy-ShowCapacity-1.0.9
WarperSan-ShipInventory-1.1.1
JulianMods-OpenMonitors-1.1.1
CTNOriginals-MonitorDoorButtons-1.1.1
NotAtomicBomb-TerminalApi-1.5.5
NotAtomicBomb-Terminal_Clock-1.0.6
coderCleric-Poltergeist-1.1.1
mrov-MrovLib-0.2.4
mrov-TerminalFormatter-0.2.23
WhiteSpike-Interactive_Terminal_API-1.1.3
malco-Lategame_Upgrades-3.10.2
mrgrm7-LethalCasino-0.5.5
Evaisa-FixPluginTypesSerialization-1.1.1
Sigurd-CSync-5.0.1
Kittenji-Groan_Tube_Scrap-1.0.2
Scintesto-Monster_Plushies-1.2.9
Theronguard-Emergency_Dice-1.1.26
DrinkableWater-Brutal_Company_Minus-0.13.10
qwbarch-BarchLib-1.0.2
Bobbie-NAudio-2.2.2
Bobbie-UniTask-2.5.0
qwbarch-Mirage-1.8.2
SolidStone-SolidLib-1.2.2
SurfacedTeam-Surfaced-1.3.2
x753-Peepers-1.0.3
NomnomAB-RollingGiant-2.6.0
zealsprince-Locker-1.2.6
x753-Mimics-2.6.4
jaspercreations-Scopophobia-1.1.5
SolidStone-Scp_049_The_Plague_Doctor-1.0.2
Ccode_lang-SirenHead-2.0.1
MaxWasUnavailable-LethalModDataLib-1.2.2
IAmBatby-LethalLevelLoader-1.3.10
Badham_Mods-SCPFoundationDungeon-4.3.4
MrUnrealTeam-SchoolDungeon-1.2.6
MrUnrealTeam-SchoolMoon-1.2.1
Lordfirespeed-OdinSerializer-2022.11.9
xilophor-LethalNetworkAPI-3.3.1
Piggy-LC_Office-1.2.4
sfDesat-ViewExtension-1.3.0
AudioKnight-StarlancerMoons-2.3.3
AudioKnight-StarlancerWarehouse-1.6.7
IAmBatby-LethalToolbox-1.0.4
s1ckboy-Seichi-0.9.0
LethalMatt-Bozoros-1.0.1
Plastered_Crab-Black_Mesa_Half_Life_Moon_Interior-1.1.6
RosiePies-RoseLib-1.0.1
RosiePies-Sector0_Interior-2.0.3
RosiePies-Gordion_Sect0-2.2.2
Dantor-Dantors_Mental_Hospital-1.2.2
Yorimor-CustomStoryLogs-1.4.5
JacobG5-JLL-1.5.2
Nikki-USC_Vortex-1.2.1
RedHuskyStudios-USC_Vortex_Interiors-0.2.0
Tolian-CaltPrime-0.9.9
Zingar-Atlas_Abyss-1.2.3
Tolian-Tomb-0.2.7
Magic_Wesley-Fission-2.0.8
Magic_Wesley-Polarus-3.0.5
Magic_Wesley-Infernis-4.0.5
Magic_Wesley-Acidir-5.0.6
Magic_Wesley-Etern-4.0.7
Magic_Wesley-Asteroid13-3.0.9
Magic_Wesley-Gratar-3.0.11
Magic_Wesley-Atlantica-3.0.6
Magic_Wesley-Junic-2.0.8
Magic_Wesley-Desolation-2.0.6
Magic_Wesley-Oldred-2.0.9
Repyl-PeterGriffinHouse-5.0.1
chill73-CoconutMall-2.1.1
Zingar-SecretLabs-3.4.1
skidz-PoolRooms-0.1.22
Magic_Wesley-WesleysInteriors-1.3.13
Zehs-WesleysInteriorsAddon-1.0.1
Backrooms-Backrooms-0.1.3
Alice-DungeonGenerationPlus-1.1.2
Alice-ScarletDevilMansion-1.3.27
Entity378-BuyableShotgunPlus-1.2.1
boring-InfiniteShotgunAmmo-1.0.3
CTMods-ChatCommands-1.1.92
LethalCompanyModding-UnityDebuggerAssistant-1.4.2</pre>

</p>
</details>

Unfortunately, I have not yet had a chance to test ShipInventory alone in multiplayer.

**Comment by minimusubi** [comment]
This is still an issue with ShipInventory 1.1.4. The ship status on the client shows 0 items stored, while the host shows 5.

<details><summary>13 mods used</summary>
<pre>BepInEx-BepInExPack-5.4.2100
DiFFoZ-BepInEx_Faster_Load_AssetBundles_Patcher-0.6.4
AinaVT-LethalConfig-1.4.3
Evaisa-FixPluginTypesSerialization-1.1.1
Rune580-LethalCompany_InputUtils-0.7.7
WhiteSpike-Interactive_Terminal_API-1.1.4
Sigurd-CSync-5.0.1
WarperSan-ShipInventory-1.1.4
flerouwu-LC_FastStartup-1.1.2
CTMods-ChatCommands-1.1.92
Pooble-LCBetterSaves-1.7.3
LethalCompanyModding-UnityDebuggerAssistant-1.4.2
LethalCompanyModding-Yukieji_UnityExplorer-4.12.1</pre>
</details>

**Comment by ezz3r** [comment]
It happend to me too.

To reproduce:

1. Create new Lobby and put items in the ship.
2. New person joins your lobby

Now you have 1 item in the Ship Inventory but your friend does not have this item in the ship inventory.

**Comment by Skyblade799** [comment]
Having a similar issue. Client tried taking out an item I put in, but it didn't let them do it. I removed the items and let them put in one, and we could both remove it,but they still saw the now removed items as well. I then put the item back in, and they could remove it, but again it showed the original items + the real item (and I didn't see the original/removed items).

**Comment by WarperSan** [comment]
Probably fixed in v1.2.0

If needed, I will reopen it
