### ISSUE TITLE
[SUGGESTION] Allow repositioning of the chute

### ISSUE THREAD

**Issue by yumm-dev** [WarperSan/ShipInventory#16]
**Is your feature request related to a problem? Please describe.**
With certain mods (ex. [Two-Story Ship](https://thunderstore.io/c/lethal-company/p/MelanieMelicious/MelanieMelicious_2_sToRy_ShIp__works_w_Wider_Ship_Mod/)), the chute kind of hangs off a bit as the wall that is usually completely flat is instead cut off as more space is added behind it. Instead of having to make a compatibility fix for every mod that it causes issues with (in the positioning aspect specifically), it would be much better and more intuitive if the chute could instead be repositioned somewhere else.

**Describe the solution you'd like**
For repositioning the Chute, I have two ideas as to how this could be implemented. One could be that it's treated like a furniture object, where pressing the build bind (B by default) would allow you to move it somewhere else, with the restrictions of it having to be on a wall with it not clipping into something else. Alternatively, it could instead be implemented as part of the config file, allowing the chute's position to be modified directly and precisely using a set of coordinates (not much of a coder but I think it would be called a Vector3 or something.) This way it can be quite precise and doesn't require manually moving it to the desired spot every time you make a new save, and it could be reloadable by quitting and reloading the save thanks to LethalConfig already being a dependency.

**Describe why you think this should be a feature and not its own mod**
The feature itself is much too quality-of-life to have its own mod, as the feature itself requires no other mods to exist for it to be of use.

**Describe alternatives you've considered**
The only other alternative I can think of is making a compat fix for each and every mod that makes a ship model change (given it disrupts the look or functionality of the chute itself), but that would be incredibly tedious and probably inefficient. The methods I have presented would not only solve most of these issues (if not requiring some player input), but would also affect those using the mod solo positively as it allows for more versatility and creativity in where the chute object can be placed.

**Additional context**
The screenshot below shows the chute while the Two-Story Ship mod is active. Notice how some of it hangs off the wall.
![The ShipInventory Chute a bit hung off of the wall.](https://github.com/user-attachments/assets/45acf54c-099d-4fa6-bfc8-e842faf804d0 "The hanging chute on the modified wall due to the Two-Story Ship mod being installed.")

**Comment by WarperSan** [comment]
Added in https://github.com/WarperSan/ShipInventory/commit/a2d68f418c67ecf0e738b15b53d921f3a0cc56ca
