### ISSUE TITLE
[BUG] Permanent Item Effects

### ISSUE THREAD

**Issue by PenguCCN** [WarperSan/ShipInventory#24]
**Describe the bug**
Compatibility issue with Lacrimosum. Placing an item that directly affects character status into the ship inventory causes the player to be permanently affected until it's removal.

**To Reproduce**
If applicable, how to reproduce the bug. You can write in this format:
1. Get speed or healing item.
2. Place into ship inventory chute.
3. See Error

**Comment by WarperSan** [comment]
Out of date mod
