### ISSUE TITLE
[BUG] Apparatus Item 

### ISSUE THREAD

**Issue by ezz3r** [WarperSan/ShipInventory#26]
**Describe the bug**
If i put the Appratus in the Ship Inventory. I cant retrieve it out. It goes out visually but when i take the item in the hand the game breaks.
I can't drop the Appratus Item and have to restart the game.

**To Reproduce**
1. Put Appratus Item in the Ship Inventory
2. Retrieve it via terminal
3. Appratus is in the Ship Inventory (Visually)
4. Take the item

**Mods used**
This is the modpack i am using: https://thunderstore.io/c/lethal-company/p/boost/Boostpack/

**Comment by WarperSan** [comment]
I tested and the Apparatus (not the Egyptian one) seems to be blacklisted. This kinda solved the problem.
