### ISSUE TITLE
My chute has been implemented incorrectly

### ISSUE THREAD

**Issue by pidbul530** [WarperSan/ShipInventory#4]
![20240902120343_1](https://github.com/user-attachments/assets/85bbb8ec-887a-46d1-9c0e-d4a7b50e9476)

I have no idea how did the engineer fail THAT hard on instaling the inventory, but it's twisted 90° to the left and about 90° forward. I can deposit items only from a veeeeery thin line where the front faces the floor and probably more than half of the items (at least that I currently have in game) are too small, to be retrievable after depositing (too small means at least the size of a prezent). I'm somewhat sure the problem appeared only after v60-62

**Comment by WarperSan** [comment]
It is possible that an error occurred when loading the chute. If you encounter the error again, please post the log so I can take a better look at it

**Comment by WarperSan** [comment]
I'm closing this issue since it is probably a _one time_ bug. The chute seems to be correctly oriented in the latest version (v1.1.1 in v64).
