### ISSUE TITLE
Loot in the shute not displaying correctly in the ship monitor created by General Improvements

### ISSUE THREAD

**Issue by Rayquaza1090** [WarperSan/ShipInventory#6]
Hello,

I used two mods in conjunction seamlessly in patch 56; this one, and General Improvements. The idea was that GI would create the extra monitors which I would configure to show scrap, and the scrap stored in the chute would be automatically calculated and subsequently displayed.

Unfortunately I'm not able to find a way to play in a specific part of the game forever, so when I forcibly got updated to v62 the feature broke. Sometimes it works correctly, like if I deposit a reactor into the chute, the total price still displays correctly on the monitor, but after adding a flask, it deducts the sum of both items from the ship.

I wasn't sure to go to first with this issue, as I can see both mod creators redirecting me to each others' github, but I just wanted to see if the cause issue was at least identifiable, first. I would try to attach logs or something to help, but I wasn't able to find anything particularly incriminating in the console that would point towards the culprit of this.

Thanks.

**Comment by ytitnE** [comment]
For me its shows 0 for any scrap going in, except for the last one, which will still show the scrap value of that item. Probably cause the way GI updates the scrapship value. Would love to see this back, cause I really like to be able to see how much scrap I have at a glance. Love the mod, I appreciate the hard work you put into this. Also, GI just recently included the amount of how many items are on the ship with scrapship value, having that update with shipinv would be awesome, but I understand if you can't.

Edit: Just did a little testing, pretty much every scrap going in will show the amount on the monitor, but it'll update when you drop or pickup an item on the ship it updates it showing 0 for any item that went in, I don't know if this info helps, just wanted to help in any way.

**Comment by WarperSan** [comment]
This issue is mostly unrelated to this mod. In the next update, the chute will entirely become incompatible with GeneralImprovements (other bugs came from this). Until the author of GI implements a way for me to (more) easily make it possible, this will remain off my TODO list.
