### ISSUE TITLE
Suggestion - Allow this to be a ship upgrade

### ISSUE THREAD

**Issue by KKaydoom** [WarperSan/ShipInventory#7]
This would be more balanced if you had to purchase the chute and maybe even be able to upgrade the storage making this an upgrade would also appeal to people like me who want progression this change would be like how they let you make reserved slots a upgrade in their new update.

**Comment by WarperSan** [comment]
Added in https://github.com/WarperSan/ShipInventory/commit/a2d68f418c67ecf0e738b15b53d921f3a0cc56ca
