### ISSUE TITLE
[BUG] Desync with QualityCompany

### ISSUE THREAD

**Issue by EisiaDEV** [WarperSan/ShipInventory#8]
**Describe the bug**
Not syncing with QualityCompany

**To Reproduce**
If applicable, how to reproduce the bug. You can write in this format:
1. Install QualityCompany and ShipInventory
2. Get any scrap and check QualityCompany's value text appearing normally above of inventory slot.
3. Insert scrap into ShipInventory's chute.
4. scrap is saved in ShipInventory, but QualityCompany's value text didn't disappeared.

**Expected behavior (Optional)**
when insert scrap into ShipInventory's chute, QualityCompany's value text would be disappear.

**Screenshots**
![ef781cc34c743d92](https://github.com/user-attachments/assets/84b9efd3-967d-4365-9384-41b59726da61)

**Mods used**
0191d6f7-4dc8-0a07-0465-da9a22c29b89
This is my mods, but it would be didn't need.

**Additional context**
This is my mod code, but you probably don't need it. It's just a visual issue and it doesn't affect the progress of the game. Also, QualityCompany has a problem where the value text don't disappear even if you use the key, so it maybe problem caused by QualityCompany.

**Comment by WarperSan** [comment]
Issue has been transferred to [this issue](https://github.com/remiX-/QualityCompany/issues/28)
