### ISSUE TITLE
[BUG] Incompatibility with the mod Wider Ship

### ISSUE THREAD

**Issue by WarperSan** [WarperSan/ShipInventory#9]
**Describe the bug**
After buying the expansion, the chute is stuck in the air.

**Expected behavior (Optional)**
The chute can be moved so we can put it anywhere.

**Screenshots**
![image](https://github.com/user-attachments/assets/b9a3431d-6880-4996-b0d3-be0fa6b60957)

**Mods used**
- [Wider Ship](https://thunderstore.io/c/lethal-company/p/mborsh/Wider_Ship_Mod)

**Comment by VineDiamond** [comment]
There is this fix if you want to use it
https://thunderstore.io/c/lethal-company/p/AtomicStudio/ShipInventory_WiderShipFix/
